apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
