apiVersion: v1
kind: Service
metadata:
  name: articles-scraper-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: articles-scraper
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}