apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: {{ .Values.phpmyadmin.port }}
      targetPort: 80
  type: NodePort
